#!/bin/sh

cd ~
if [ -d /opt/echbay_kdata ]; then
rm -rf /opt/echbay_kdata/*
rm -rf /opt/echbay_kdata
sleep 5
fi

echo "Install git..."
sudo yum -y install git > /dev/null 2>&1

# update code
if [ -d /opt/echbay_kdata ]; then
cd ~ ; cd /opt/echbay_kdata && git pull ; cd ~
#git commit -m "ECHBAY-VPSSIM commit"
#git pull origin master
#git pull origin
#git merge origin master
# or clone new
else
git clone https://github.com/itvn9online/kdata-free /opt/echbay_kdata
fi

cd ~

sleep 5

find /opt/echbay_kdata/script/kdata/menu -type f -exec chmod 755 {} \;
/opt/echbay_kdata/script/kdata/menu/git-clone-done

echo "update ECHBAY-VPSSIM menu"
mkdir -p /etc/kdata/menu ; chmod 755 /etc/kdata/menu
rm -rf /etc/kdata/menu/*
yes | cp -rf /opt/echbay_kdata/script/kdata/menu/. /etc/kdata/menu/

echo "Chmod 755 Menu"
/opt/echbay_kdata/script/kdata/menu/chmod-755-menu
