#!/bin/sh
. /home/kdata.conf
if [ "$(redis-cli ping)" = "PONG" ]; then
redistatus=Working
else
redistatus=Stopped
fi
prompt="Nhap lua chon cua ban: "
options=("Clear Redis Cache" "Cau hinh Redis" "Kiem tra Redis Status" "Thoat")
printf "=========================================================================\n"
printf "                KDATA - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                           Quan Ly Redis Cache                                \n"
printf "=========================================================================\n"
printf "          Redis: $redistatus - Ram Max: $(grep maxmemory /etc/redis/redis.conf | awk 'NR==1 {print $2}' | sed 's/mb//') M  - Ram Using: $(redis-cli INFO | grep used_memory_human | sed 's/used_memory_human://') \n"
printf "=========================================================================\n"


PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/kdata/menu/kdata-clear-redis;;
    2) /etc/kdata/menu/kdata-redis-change-size;;
    3) /etc/kdata/menu/kdata-check-redis-status;;
    4) clear && kdata;; 
    0) clear && kdata;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu ";continue;;

    esac
done
 
