#!/bin/bash
. /home/kdata.conf

# copy code tu file install sang
cd ~
wget --no-check-certificate -q https://raw.githubusercontent.com/vuukhanhduy/kdata-vps/master/scripts/kdata/menu/git-clone
chmod +x /root/git-clone
bash /root/git-clone


# BEGIN update VPSKDATA main
#rm -rf /etc/motd
yes | cp -rf /opt/kdata_vps/script/kdata/motd /etc/motd

yes | cp -rf /opt/kdata_vps/script/kdata/calc /bin/calc && chmod +x /bin/calc

yes | cp -rf /opt/kdata_vps/script/kdata/kdata /bin/kdata && chmod +x /bin/kdata
# BEGIN update VPSKDATA main


rm -rf /home/kdata.demo/errorpage_html/*
yes | cp -rf /opt/kdata_vps/script/kdata/errorpage_html/. /home/kdata.demo/errorpage_html/


# BEGIN update VPSKDATA menu
#rm -rf /etc/kdata/menu/*
#yes | cp -rf /opt/kdata_vps/script/kdata/menu/. /etc/kdata/menu/

# Chmod 755 Menu
#/opt/kdata_vps/script/kdata/menu/chmod-755-menu
# END update VPSKDATA menu


# confirm done update
yes | cp -rf /opt/kdata_vps/version /etc/kdata/kdata.version


#rm -rf /opt/kdata_vps/*
#rm -rf /opt/kdata_vps
sleep 1

# enable auto update system
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
if [ -f /etc/kdata/menu/auto-update-system ]; then
clear && bash /etc/kdata/menu/auto-update-system
fi
else
echo "Auto update system in CentOS 7 only"
/etc/kdata/menu/kdata-update-upgrade-service-menu
fi

#exit
